create table if not exists public.students (
 id bigint generated by default as identity primary key,
 student_number integer not null unique,
 name text not null,
 national_id text not null unique,
 student_code text not null,
 gender text,
 class_name text not null,
 school_file_number text,
 created_at timestamptz default now()
);
create table if not exists public.registrations (
 id bigint generated by default as identity primary key,
 student_id bigint references public.students(id) on delete cascade,
 student_phone text not null,
 father_phone text not null,
 address text not null,
 registered_at timestamptz default now(),
 unique(student_id)
);
create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade);
create or replace function public.find_student_by_national_id(p_national_id text)
returns table(id bigint,student_number integer,name text,national_id text,student_code text,gender text,class_name text,school_file_number text,registered boolean)
language sql security definer set search_path=public as $$
 select s.id,s.student_number,s.name,s.national_id,s.student_code,s.gender,s.class_name,s.school_file_number,(r.id is not null)
 from public.students s left join public.registrations r on r.student_id=s.id where s.national_id=trim(p_national_id) limit 1;
$$;
create or replace function public.register_student(p_student_id bigint,p_student_phone text,p_father_phone text,p_address text)
returns void language plpgsql security definer set search_path=public as $$
begin
 if exists(select 1 from registrations where student_id=p_student_id) then raise exception 'ALREADY_REGISTERED'; end if;
 insert into registrations(student_id,student_phone,father_phone,address) values(p_student_id,trim(p_student_phone),trim(p_father_phone),trim(p_address));
end $$;
create or replace function public.is_admin() returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()); $$;
create or replace function public.admin_student_list()
returns table(id bigint,student_number integer,name text,national_id text,student_code text,gender text,class_name text,school_file_number text,student_phone text,father_phone text,address text,registered_at timestamptz,registered boolean)
language sql security definer set search_path=public as $$
 select s.id,s.student_number,s.name,s.national_id,s.student_code,s.gender,s.class_name,s.school_file_number,r.student_phone,r.father_phone,r.address,r.registered_at,(r.id is not null)
 from students s left join registrations r on r.student_id=s.id where public.is_admin() order by s.student_number;
$$;
